### ISSUE TITLE
Review lesson 5: ggplot

### ISSUE THREAD

**Issue by anisfeld** [harris-coding-lab/harris-coding-lab.github.io#16]
Purpose: Make sure the slides and videos are aligned, and that students can easily access the material.

This is not ready for Review yet.

When I make these, I'll send you a notification and you'll be able to find the links to the video and slides, at  [harris-coding-lab.github.io](harris-coding-lab.github.io )

# Update Rmd, pdf and R file in pull request

Please check the box as you go!

- [x] Watch the video with slides open. Make sure the order is roughly the same. 
    - [x] If essential code is missing from slides, please add a slide. (I don't think this should be the case.)
    - [x] Move slides in the Rmd and knit, so we have an updated pdf and Rmd. (I think out of order slides is likely.)

- [x] create a `.R` file with the code used in the slides. Name the file identically to Rmd and place in `code` folder (e.g. code from `slides/00_intro.Rmd` becomes `code/00_intro.R`) (You can see examples in the code folder)

# Provide feedback about content in comments on this issue ticket

- [x] is there anything that could be explained more clearly? ideas?
- [x] am I making unwarranted assumptions about background knowledge?
- [x] let me know if anything is weird in videos with editting, etc.

**Comment by vfuentesc** [comment]
1. The code will require the `maps` package. I've included it in the libraries chunk
2. `geom_smooth` visualizations are using `se = FALSE` in slide, but `se = TRUE` (or omitted) in the video. I think the CI would help to differentiate `geom_line` from `geom_smooth` because it has different colors. What do you think?
3. The slide "Visualizing the mapping with a geom" appears three times in the video. I think those in 9:43-9:47 and 10:32-10:36  may be removed since they're breaking the video's line
4. Editing minor issue: there are empty seconds in the video between 10:40 and 10:47
5.  The "discrete vs continuous data" slide wasn't knitting properly. I inserted an additional line to correct it.
6. I got smaller slides when I knit the `.rmd` file. I don't know why, and I've tried several alternatives. Could you make the final knit?
