### ISSUE TITLE
Review lab material 1

### ISSUE THREAD

**Issue by anisfeld** [harris-coding-lab/harris-coding-lab.github.io#23]
Go through the lab material as if you were a student.

- [x] Suggest edits for clarity
- [x] Add challenge to the beginning of the problems if they seem particularly difficult.
- [x] Make a pull request.

Please reach out to me with any questions about any of this.

**Comment by domteo95** [comment]
Some minor edits that I'm suggesting in my PR:
 *im also unable to knit the edited rmd file into a pdf because in the rmd file there's an include_graphics('...data_structure.jpeg') but I can't find the image in the repo so it won't knit. 

Working with data & scripts: 
- Useful to explain why you use readxl::read_xlsx(...) instead of just read_xlsx(...)
```
 wid_data_raw <- readxl::read_xlsx("world_wealth_inequality.xlsx",
col_names = c("country", "indicator", "percentile", "year", "value"))
```

Manipulating inequality with dplyr:
- `french_data %>% filter( ... , ...)` should be `french_data <- wid_data  %>% filter( ... , ...)`instead, to avoid confusion since it's the first instance where we run into the french_data variable and have yet to create this variable. 
- 6th question is labeled as 1st question again in the pdf. 
- 6th question it should be summarize(...) instead of arrange(...) 

*None appear particularly challenging
